version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  webserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: my-fake-news-secret
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml_code:/opt/airflow/ml_code
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    command: bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver"

  scheduler:
    build: .
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: my-fake-news-secret
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml_code:/opt/airflow/ml_code
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    command: bash -c "airflow scheduler"
